### ISSUE TITLE
BoundingBox er et punkt

### ISSUE THREAD

**Issue by jarped** [kartverket/SFKB-API#11]
https://github.com/kartverket/SFKB-API/blob/0bba94026a39a83ea845b71c5728fda05e89ccac/spec/openapi.yaml#L369

BoundingBox er bare et punkt. Feltene ll og ur må begge være et punkt for å lage en boks.

Se WFS3.0:
https://github.com/opengeospatial/WFS_FES/blob/master/openapi.yaml#L205

**Comment by jarped** [comment]
Forslag til endring:
```
    BoundingBox:
      type: object
      properties:
        ll:
          type: array
          minItems: 2
          maxItems: 2
          items:
            type: number
            format: double
        ur:
          type: array
          minItems: 2
          maxItems: 2
          items:
            type: number
            format: double
```
